import { useEffect, useMemo, useState } from 'react';
type Terminal='battery_plus'|'battery_minus'|'lamp_plus'|'lamp_minus'|'switch_in'|'switch_out';
type Connection={from:Terminal;to:Terminal};
const correct=new Set(['battery_plus|lamp_plus','lamp_minus|switch_in','switch_out|battery_minus']);
const labels:Record<Terminal,string>={battery_plus:'Battery +',battery_minus:'Battery −',lamp_plus:'Lamp +',lamp_minus:'Lamp −',switch_in:'Switch IN',switch_out:'Switch OUT'};
const canon=(a:Terminal,b:Terminal)=>{const x=`${a}|${b}`,y=`${b}|${a}`;return correct.has(x)?x:y};
export default function App(){
 const[connections,setConnections]=useState<Connection[]>([]),[selected,setSelected]=useState<Terminal|null>(null),[closed,setClosed]=useState(false),[time,setTime]=useState(180),[submitted,setSubmitted]=useState(false),[score,setScore]=useState<number|null>(null),[feedback,setFeedback]=useState('');
 useEffect(()=>{if(submitted||time<=0)return;const id=setInterval(()=>setTime(t=>Math.max(0,t-1)),1000);return()=>clearInterval(id)},[submitted,time]);
 const complete=useMemo(()=>closed&&connections.length===3&&connections.every(c=>correct.has(canon(c.from,c.to))),[closed,connections]);
 const select=(id:Terminal)=>{if(submitted)return;if(!selected){setSelected(id);return}if(selected!==id&&!connections.some(c=>(c.from===selected&&c.to===id)||(c.from===id&&c.to===selected)))setConnections(v=>[...v,{from:selected,to:id}]);setSelected(null)};
 const submit=async()=>{if(submitted)return;const payload={connections:connections.map(c=>({from_terminal:c.from,to_terminal:c.to})),elapsed_seconds:180-time};try{const r=await fetch('http://localhost:8000/api/activities/circuit-lamp/evaluate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error();const d=await r.json();setScore(d.score);setFeedback(d.feedback)}catch{const s=connections.filter(c=>correct.has(canon(c.from,c.to))).length;setScore(complete?100:Math.round(s/3*70));setFeedback(complete?'Circuit complete. The lamp can receive a closed electrical path.':'The circuit is incomplete. Check each terminal and make one continuous path through the lamp and switch.')}setSubmitted(true)};
 const reset=()=>{setConnections([]);setSelected(null);setClosed(false);setTime(180);setSubmitted(false);setScore(null);setFeedback('')};
 const mm=String(Math.floor(time/60)).padStart(2,'0'),ss=String(time%60).padStart(2,'0');
 return <div className="shell"><header><div><small>ELECTRICAL COMPETENCY ASSESSMENT</small><h1>Practical Assessment</h1></div><div className="timer"><small>TIME</small><b>{mm}:{ss}</b></div></header><main><section className="panel"><div className="head"><div><span className="tag">PRACTICAL • BEGINNER</span><h2>Connect the wires to turn ON the light</h2><p>Click a terminal, then click the terminal it should connect to. Build the circuit and close the switch.</p></div><strong>{Math.round(connections.length/3*100)}%</strong></div><div className="instruction"><b>Target:</b> Battery + → Lamp +, Lamp − → Switch IN, Switch OUT → Battery −. Then close the switch.</div><div className="bench"><svg viewBox="0 0 1000 500">{connections.map((c,i)=>{const p:Record<Terminal,[number,number]>={battery_plus:[150,150],battery_minus:[150,350],lamp_plus:[500,150],lamp_minus:[500,350],switch_in:[850,150],switch_out:[850,350]};return <line key={i} x1={p[c.from][0]} y1={p[c.from][1]} x2={p[c.to][0]} y2={p[c.to][1]} className="wire"/>})}</svg><div className="part battery"><b>BATTERY</b><div className="battery-shape">+ &nbsp; ┃ ┃ ┃ ┃ &nbsp; −</div><T id="battery_plus" s={selected==='battery_plus'} on={select}/><T id="battery_minus" s={selected==='battery_minus'} on={select}/></div><div className={`part lamp ${complete?'on':''}`}><b>LAMP</b><div className="bulb">{complete?'●':'○'}</div><T id="lamp_plus" s={selected==='lamp_plus'} on={select}/><T id="lamp_minus" s={selected==='lamp_minus'} on={select}/></div><div className="part sw"><b>SWITCH</b><button className={`switch ${closed?'closed':''}`} onClick={()=>!submitted&&setClosed(v=>!v)}><i/><em/></button><span>{closed?'CLOSED':'OPEN'}</span><T id="switch_in" s={selected==='switch_in'} on={select}/><T id="switch_out" s={selected==='switch_out'} on={select}/></div></div><div className="connections"><b>Connections</b>{connections.length===0?<p>No wires connected yet.</p>:connections.map((c,i)=><div key={i}>{labels[c.from]} <span>→</span> {labels[c.to]} <button onClick={()=>!submitted&&setConnections(v=>v.filter((_,n)=>n!==i))}>Remove</button></div>)}</div><div className="actions"><button onClick={reset}>Reset</button><button className="primary" disabled={submitted} onClick={submit}>Submit Assessment</button></div></section><aside><div className="card"><b>Assessment</b><p>Activity <strong>1 / 1</strong></p><p>Maximum score <strong>100</strong></p><p>Time limit <strong>3:00</strong></p></div><div className="card"><b>How it works</b><p>1. Select a terminal.</p><p>2. Select its destination.</p><p>3. Close the switch.</p><p>4. Submit your result.</p></div><div className="result">{score===null?<><small>LIVE STATUS</small><h3>{complete?'Circuit ready':'Assessment in progress'}</h3><p>{complete?'Close the switch and submit.':'Connect the required terminals.'}</p></>:<><small>YOUR RESULT</small><h3>{score}<span>/100</span></h3><p>{feedback}</p><button onClick={reset}>Try Again</button></>}</div></aside></main></div>
}
function T({id,s,on}:{id:Terminal;s:boolean;on:(id:Terminal)=>void}){return <button className={`terminal ${s?'selected':''}`} onClick={()=>on(id)}>{id.includes('plus')?'+':id.includes('minus')?'−':id==='switch_in'?'IN':'OUT'}</button>}
