import { useSyncExternalStore } from 'react';

export type Language = 'en' | 'hi' | 'or';

let currentLanguage: Language = (typeof window !== 'undefined' && (localStorage.getItem('assessment-language') as Language)) || 'en';
const listeners = new Set<() => void>();

export function setLanguage(language: Language) {
  currentLanguage = language;
  if (typeof window !== 'undefined') localStorage.setItem('assessment-language', language);
  listeners.forEach(listener => listener());
}
export function useLanguage(): Language {
  useSyncExternalStore((onChange) => { listeners.add(onChange); return () => listeners.delete(onChange); }, () => currentLanguage, () => currentLanguage);
  return currentLanguage;
}

const hi: Record<string,string> = {
'Choose the module you want to be assessed on':'जिस मॉड्यूल का मूल्यांकन करना चाहते हैं उसे चुनें','ELECTRICAL':'इलेक्ट्रिकल','MECHANICAL':'मैकेनिकल','INSTRUMENTATION & PLC':'इंस्ट्रुमेंटेशन और PLC','CIVIL & INFRA':'सिविल और इंफ्रा','Select Module':'मॉड्यूल चुनें','Each module contains MCQ, Scenario-Based Questions and Practical Activities.':'प्रत्येक मॉड्यूल में MCQ, परिदृश्य-आधारित प्रश्न और व्यावहारिक गतिविधियाँ शामिल हैं।',
'Test your knowledge and practical skills in electrical systems and maintenance.':'विद्युत प्रणालियों और रखरखाव में अपने ज्ञान और व्यावहारिक कौशल का परीक्षण करें।','Evaluate your mechanical maintenance and troubleshooting skills.':'अपने मैकेनिकल रखरखाव और ट्रबलशूटिंग कौशल का मूल्यांकन करें।','Assess your instrumentation, control systems and PLC knowledge.':'इंस्ट्रुमेंटेशन, कंट्रोल सिस्टम और PLC के अपने ज्ञान का मूल्यांकन करें।','Test your civil construction and infrastructure competency.':'सिविल निर्माण और इंफ्रास्ट्रक्चर में अपनी दक्षता का परीक्षण करें।',
'Electrical Fundamentals':'इलेक्ट्रिकल फंडामेंटल्स','Assessment':'मूल्यांकन','Fundamentals':'फंडामेंटल्स','Technical validation':'तकनीकी सत्यापन','Practical wiring':'व्यावहारिक वायरिंग','Circuit assembly':'सर्किट असेंबली','Performance report':'प्रदर्शन रिपोर्ट','Question navigator':'प्रश्न नेविगेटर','Select any question number':'कोई भी प्रश्न संख्या चुनें','Answered':'उत्तर दिया','Skipped':'छोड़ा गया','Current':'वर्तमान','Not visited':'नहीं देखा गया','Previous':'पिछला','Skip question →':'प्रश्न छोड़ें →','Finish quiz →':'क्विज़ समाप्त करें →','Next →':'अगला →','Finish now':'अभी समाप्त करें',
'Practical Validation':'व्यावहारिक सत्यापन','Build the 12V Lamp Circuit':'12V लैम्प सर्किट बनाएं','Material Tray':'सामग्री ट्रे','Select wire colour':'वायर का रंग चुनें','Red':'लाल','Blue':'नीला','Black':'काला','Supply / positive':'सप्लाई / पॉजिटिव','Control / load':'कंट्रोल / लोड','Return / negative':'रिटर्न / नेगेटिव','Assembly & Wiring Area':'असेंबली और वायरिंग क्षेत्र','Connection Objective':'कनेक्शन उद्देश्य','Finish practical →':'व्यावहारिक समाप्त करें →',
'Technical Activity':'तकनीकी गतिविधि','Electrical Competency Assessment':'इलेक्ट्रिकल दक्षता मूल्यांकन','Electrical Troubleshooting Lab':'इलेक्ट्रिकल ट्रबलशूटिंग लैब','Scenario Challenge — Why Is the Bulb Dead?':'परिदृश्य चुनौती — बल्ब बंद क्यों है?','FIELD DIAGNOSIS':'फील्ड डायग्नोसिस','Technician rule':'तकनीशियन नियम','Inspect the physical circuit before choosing a diagnosis.':'निदान चुनने से पहले भौतिक सर्किट का निरीक्षण करें।','Record diagnosis':'निदान दर्ज करें','Diagnosis recorded':'निदान दर्ज किया गया','Continue →':'जारी रखें →','Correct diagnosis':'सही निदान','Diagnosis review':'निदान समीक्षा','Your answer:':'आपका उत्तर:','Correct answer:':'सही उत्तर:',
'3D Interactive Workbench':'3D इंटरैक्टिव वर्कबेंच','REPOSITORY 3D ELEMENTS':'रिपॉजिटरी 3D एलिमेंट्स','Drag = rotate view':'ड्रैग = दृश्य घुमाएँ','Wheel = zoom':'व्हील = ज़ूम','Right-drag = pan':'राइट-ड्रैग = पैन','Circuit is fixed — rotate only':'सर्किट स्थिर है — केवल घुमाएँ',
'Electrical Circuit Assembly':'इलेक्ट्रिकल सर्किट असेंबली','Components':'घटक','Circuit complete.':'सर्किट पूरा हुआ।','Finish activity →':'गतिविधि समाप्त करें →','Retake assessment ↻':'मूल्यांकन फिर से करें ↻',
'What is the SI unit of electrical current?':'विद्युत धारा की SI इकाई क्या है?','Volt':'वोल्ट','Ampere':'एम्पियर','Ohm':'ओम','Watt':'वाट','Which instrument measures electrical current?':'विद्युत धारा को कौन-सा उपकरण मापता है?','Voltmeter':'वोल्टमीटर','Ammeter':'एमीटर','Ohmmeter':'ओममीटर','Wattmeter':'वाटमीटर',"Which equation represents Ohm's law?":'कौन-सा समीकरण ओम के नियम को दर्शाता है?','What is the SI unit of resistance?':'प्रतिरोध की SI इकाई क्या है?','What is the primary purpose of a fuse?':'फ्यूज़ का मुख्य उद्देश्य क्या है?','Increase voltage':'वोल्टेज बढ़ाना','Protect against excessive current':'अत्यधिक धारा से सुरक्षा','Store energy':'ऊर्जा संग्रह करना','Measure current':'धारा मापना','In a series circuit, total resistance is:':'श्रृंखला परिपथ में कुल प्रतिरोध होता है:','The sum of resistances':'प्रतिरोधों का योग','Always zero':'हमेशा शून्य','The smallest resistance':'सबसे छोटा प्रतिरोध','The largest resistance':'सबसे बड़ा प्रतिरोध','Which current periodically changes direction?':'कौन-सी धारा समय-समय पर दिशा बदलती है?','Static current':'स्थिर धारा','Leakage current':'लीकेज धारा','What is the SI unit of electrical power?':'विद्युत शक्ति की SI इकाई क्या है?','Coulomb':'कूलॉम','In an ideal parallel circuit, what is common across each branch?':'आदर्श समानांतर परिपथ में प्रत्येक शाखा में क्या समान होता है?','Voltage':'वोल्टेज','Resistance':'प्रतिरोध','Power':'शक्ति','Energy':'ऊर्जा','Which device opens or closes an electrical circuit?':'कौन-सा उपकरण विद्युत परिपथ को खोलता या बंद करता है?','Transformer':'ट्रांसफॉर्मर','Switch':'स्विच','Resistor':'रेज़िस्टर','Capacitor':'कैपेसिटर',
'The wire is disconnected near the switch, creating an open circuit.':'स्विच के पास तार डिस्कनेक्ट है, जिससे ओपन सर्किट बन गया है।','The battery polarity is reversed, so the bulb cannot receive power.':'बैटरी की ध्रुवीयता उलटी है, इसलिए बल्ब को बिजली नहीं मिल सकती।','The bulb is short-circuited by another wire, bypassing the lamp.':'एक अन्य तार ने बल्ब को बायपास करते हुए शॉर्ट सर्किट बना दिया है।','The bulb has too much resistance for the battery to supply current.':'बल्ब का प्रतिरोध इतना अधिक है कि बैटरी पर्याप्त धारा नहीं दे सकती।',
'What most likely happened to the circuit and is causing the bulb to remain off?':'सर्किट में सबसे संभावित रूप से क्या हुआ है जिसके कारण बल्ब बंद है?'
};

const od: Record<string,string> = {
'Choose the module you want to be assessed on':'ଆପଣ ଯେଉଁ ମଡ୍ୟୁଲରେ ମୂଲ୍ୟାଙ୍କନ ହେବାକୁ ଚାହୁଁଛନ୍ତି ତାହା ବାଛନ୍ତୁ','ELECTRICAL':'ଇଲେକ୍ଟ୍ରିକାଲ','MECHANICAL':'ମେକାନିକାଲ','INSTRUMENTATION & PLC':'ଇନ୍ଷ୍ଟ୍ରୁମେଣ୍ଟେସନ୍ ଏବଂ PLC','CIVIL & INFRA':'ସିଭିଲ୍ ଏବଂ ଇନ୍ଫ୍ରା','Select Module':'ମଡ୍ୟୁଲ ବାଛନ୍ତୁ','Each module contains MCQ, Scenario-Based Questions and Practical Activities.':'ପ୍ରତ୍ୟେକ ମଡ୍ୟୁଲରେ MCQ, ପରିସ୍ଥିତି-ଆଧାରିତ ପ୍ରଶ୍ନ ଏବଂ ପ୍ରାୟୋଗିକ କାର୍ଯ୍ୟକଳାପ ରହିଛି।',
'Test your knowledge and practical skills in electrical systems and maintenance.':'ବିଦ୍ୟୁତ୍ ପ୍ରଣାଳୀ ଓ ରକ୍ଷଣାବେକ୍ଷଣରେ ଆପଣଙ୍କ ଜ୍ଞାନ ଓ ପ୍ରାୟୋଗିକ ଦକ୍ଷତା ପରୀକ୍ଷା କରନ୍ତୁ।','Evaluate your mechanical maintenance and troubleshooting skills.':'ମେକାନିକାଲ୍ ରକ୍ଷଣାବେକ୍ଷଣ ଓ ଟ୍ରବଲସୁଟିଂ ଦକ୍ଷତାର ମୂଲ୍ୟାଙ୍କନ କରନ୍ତୁ।','Assess your instrumentation, control systems and PLC knowledge.':'ଇନ୍ଷ୍ଟ୍ରୁମେଣ୍ଟେସନ୍, କଣ୍ଟ୍ରୋଲ୍ ସିଷ୍ଟମ୍ ଓ PLC ଜ୍ଞାନର ମୂଲ୍ୟାଙ୍କନ କରନ୍ତୁ।','Test your civil construction and infrastructure competency.':'ସିଭିଲ୍ ନିର୍ମାଣ ଓ ଇନ୍ଫ୍ରାଷ୍ଟ୍ରକ୍ଚରରେ ଆପଣଙ୍କ ଦକ୍ଷତା ପରୀକ୍ଷା କରନ୍ତୁ।',
'Electrical Fundamentals':'ଇଲେକ୍ଟ୍ରିକାଲ୍ ମୌଳିକତା','Assessment':'ମୂଲ୍ୟାଙ୍କନ','Fundamentals':'ମୌଳିକତା','Technical validation':'ଟେକ୍ନିକାଲ୍ ଯାଞ୍ଚ','Practical wiring':'ପ୍ରାୟୋଗିକ ୱାୟରିଂ','Circuit assembly':'ସର୍କିଟ୍ ଅସେମ୍ବଲି','Performance report':'ପ୍ରଦର୍ଶନ ରିପୋର୍ଟ','Question navigator':'ପ୍ରଶ୍ନ ନେଭିଗେଟର','Answered':'ଉତ୍ତର ଦିଆଗଲା','Skipped':'ଛାଡ଼ାଗଲା','Current':'ବର୍ତ୍ତମାନ','Not visited':'ଦେଖାଯାଇନାହିଁ','Previous':'ପୂର୍ବବର୍ତ୍ତୀ','Skip question →':'ପ୍ରଶ୍ନ ଛାଡ଼ନ୍ତୁ →','Finish quiz →':'କ୍ୱିଜ୍ ଶେଷ କରନ୍ତୁ →','Next →':'ପରବର୍ତ୍ତୀ →','Finish now':'ଏବେ ଶେଷ କରନ୍ତୁ',
'Practical Validation':'ପ୍ରାୟୋଗିକ ଯାଞ୍ଚ','Build the 12V Lamp Circuit':'12V ଲ୍ୟାମ୍ପ ସର୍କିଟ୍ ତିଆରି କରନ୍ତୁ','Material Tray':'ସାମଗ୍ରୀ ଟ୍ରେ','Select wire colour':'ତାରର ରଙ୍ଗ ବାଛନ୍ତୁ','Red':'ଲାଲ','Blue':'ନୀଳ','Black':'କଳା','Supply / positive':'ସପ୍ଲାଇ / ପଜିଟିଭ୍','Control / load':'କଣ୍ଟ୍ରୋଲ୍ / ଲୋଡ୍','Return / negative':'ରିଟର୍ନ / ନେଗେଟିଭ୍','Assembly & Wiring Area':'ଅସେମ୍ବଲି ଏବଂ ୱାୟରିଂ ଅଞ୍ଚଳ','Connection Objective':'କନେକ୍ସନ୍ ଉଦ୍ଦେଶ୍ୟ','Finish practical →':'ପ୍ରାୟୋଗିକ ଶେଷ କରନ୍ତୁ →',
'Technical Activity':'ଟେକ୍ନିକାଲ୍ କାର୍ଯ୍ୟକଳାପ','Electrical Competency Assessment':'ଇଲେକ୍ଟ୍ରିକାଲ୍ ଦକ୍ଷତା ମୂଲ୍ୟାଙ୍କନ','Electrical Troubleshooting Lab':'ଇଲେକ୍ଟ୍ରିକାଲ୍ ଟ୍ରବଲସୁଟିଂ ଲ୍ୟାବ','Scenario Challenge — Why Is the Bulb Dead?':'ପରିସ୍ଥିତି ଚ୍ୟାଲେଞ୍ଜ — ବଲ୍ବ କାହିଁକି ଜଳୁନାହିଁ?','FIELD DIAGNOSIS':'ଫିଲ୍ଡ ଡାୟାଗ୍ନୋସିସ୍','Technician rule':'ଟେକ୍ନିସିଆନ୍ ନିୟମ','Inspect the physical circuit before choosing a diagnosis.':'ଡାୟାଗ୍ନୋସିସ୍ ବାଛିବା ପୂର୍ବରୁ ଭୌତିକ ସର୍କିଟ୍ ଯାଞ୍ଚ କରନ୍ତୁ।','Record diagnosis':'ଡାୟାଗ୍ନୋସିସ୍ ରେକର୍ଡ କରନ୍ତୁ','Diagnosis recorded':'ଡାୟାଗ୍ନୋସିସ୍ ରେକର୍ଡ ହୋଇଛି','Continue →':'ଜାରି ରଖନ୍ତୁ →','Correct diagnosis':'ସଠିକ୍ ଡାୟାଗ୍ନୋସିସ୍','Diagnosis review':'ଡାୟାଗ୍ନୋସିସ୍ ସମୀକ୍ଷା','Your answer:':'ଆପଣଙ୍କ ଉତ୍ତର:','Correct answer:':'ସଠିକ୍ ଉତ୍ତର:','3D Interactive Workbench':'3D ଇଣ୍ଟରାକ୍ଟିଭ୍ ୱର୍କବେଞ୍ଚ','REPOSITORY 3D ELEMENTS':'ରିପୋଜିଟୋରୀ 3D ଏଲିମେଣ୍ଟସ୍','Drag = rotate view':'ଡ୍ରାଗ୍ = ଦୃଶ୍ୟ ଘୁରାନ୍ତୁ','Wheel = zoom':'ହ୍ୱିଲ୍ = ଜୁମ୍','Right-drag = pan':'ରାଇଟ୍-ଡ୍ରାଗ୍ = ପ୍ୟାନ୍','Circuit is fixed — rotate only':'ସର୍କିଟ୍ ସ୍ଥିର — କେବଳ ଘୁରାନ୍ତୁ','Electrical Circuit Assembly':'ଇଲେକ୍ଟ୍ରିକାଲ୍ ସର୍କିଟ୍ ଅସେମ୍ବଲି','Components':'ଉପାଦାନ','Circuit complete.':'ସର୍କିଟ୍ ସମ୍ପୂର୍ଣ୍ଣ ହୋଇଛି।','Finish activity →':'କାର୍ଯ୍ୟକଳାପ ଶେଷ କରନ୍ତୁ →','Retake assessment ↻':'ମୂଲ୍ୟାଙ୍କନ ପୁନର୍ବାର କରନ୍ତୁ ↻',
'The wire is disconnected near the switch, creating an open circuit.':'ସ୍ୱିଚ୍ ନିକଟରେ ତାର ବିଚ୍ଛିନ୍ନ ହୋଇ ଓପନ୍ ସର୍କିଟ୍ ସୃଷ୍ଟି ହୋଇଛି।','The battery polarity is reversed, so the bulb cannot receive power.':'ବ୍ୟାଟେରୀର ପୋଲାରିଟି ଓଲଟା ଅଛି, ତେଣୁ ବଲ୍ବକୁ ବିଦ୍ୟୁତ୍ ମିଳିପାରୁନାହିଁ।','The bulb is short-circuited by another wire, bypassing the lamp.':'ଅନ୍ୟ ଏକ ତାର ବଲ୍ବକୁ ବାଇପାସ୍ କରି ଶର୍ଟ ସର୍କିଟ୍ କରିଛି।','The bulb has too much resistance for the battery to supply current.':'ବଲ୍ବର ପ୍ରତିରୋଧ ଅତ୍ୟଧିକ ଥିବାରୁ ବ୍ୟାଟେରୀ ଆବଶ୍ୟକ ଧାରା ଯୋଗାଇପାରୁନାହିଁ।','What most likely happened to the circuit and is causing the bulb to remain off?':'ସର୍କିଟ୍‌ରେ ସମ୍ଭାବ୍ୟ କଣ ଘଟିଛି ଯାହା ଫଳରେ ବଲ୍ବ ବନ୍ଦ ରହିଛି?'
};

hi['The technician reports that the bulb is not illuminating even though the circuit contains the battery, switch, wiring and bulb. Inspect the supplied 3D circuit carefully before diagnosing the fault.']='तकनीशियन के अनुसार बल्ब नहीं जल रहा है, जबकि सर्किट में बैटरी, स्विच, वायरिंग और बल्ब मौजूद हैं। खराबी का निदान करने से पहले दिए गए 3D सर्किट का ध्यानपूर्वक निरीक्षण करें।';
od['The technician reports that the bulb is not illuminating even though the circuit contains the battery, switch, wiring and bulb. Inspect the supplied 3D circuit carefully before diagnosing the fault.']='ଟେକ୍ନିସିଆନ୍ କହୁଛନ୍ତି ଯେ ବ୍ୟାଟେରୀ, ସ୍ୱିଚ୍, ୱାୟରିଂ ଓ ବଲ୍ବ ଥିଲେ ମଧ୍ୟ ବଲ୍ବ ଜଳୁନାହିଁ। ତ୍ରୁଟି ନିର୍ଣ୍ଣୟ ପୂର୍ବରୁ ଦିଆଯାଇଥିବା 3D ସର୍କିଟ୍‌କୁ ଭଲଭାବେ ଯାଞ୍ଚ କରନ୍ତୁ।';
hi['Battery']='बैटरी'; hi['Fuse']='फ्यूज़'; hi['Switch']='स्विच'; hi['Bulb']='बल्ब'; hi['Variable resistor']='वैरिएबल रेज़िस्टर'; hi['Ammeter']='एमीटर'; hi['Placed']='रखा गया'; hi['Drag to board']='बोर्ड पर ड्रैग करें';
od['Battery']='ବ୍ୟାଟେରୀ'; od['Fuse']='ଫ୍ୟୁଜ୍'; od['Switch']='ସ୍ୱିଚ୍'; od['Bulb']='ବଲ୍ବ'; od['Variable resistor']='ଭେରିଏବଲ୍ ରେଜିଷ୍ଟର୍'; od['Ammeter']='ଆମିଟର୍'; od['Placed']='ରଖାଗଲା'; od['Drag to board']='ବୋର୍ଡକୁ ଡ୍ରାଗ୍ କରନ୍ତୁ';

export function t(language: Language, text: string): string {
  return language === 'hi' ? (hi[text] || text) : language === 'or' ? (od[text] || text) : text;
}
